//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.Friendly.Windows.Grasp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.Friendly.Windows.Grasp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Communication with the application failed.
        ///The target applcation may be unreachable or you may be trying to send
        ///data that cannot be serialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAppCommunication {
            get {
                return ResourceManager.GetString("ErrorAppCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than one window with the specified dialog ID were found on the same level.
        ///The window could not be identified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ManyFoundDialogId {
            get {
                return ResourceManager.GetString("ManyFoundDialogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since the selected GUI element does not have a Window handle, the specified method or a constructor cannot be used.
        ///Please use a different acquisition method. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotHaveWindowHandle {
            get {
                return ResourceManager.GetString("NotHaveWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target window has vanished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetWindowVanish {
            get {
                return ResourceManager.GetString("TargetWindowVanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The appointed operation can only be performed in a top-level window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TopLevelOnly {
            get {
                return ResourceManager.GetString("TopLevelOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access by AppVar is not allowed for the specified window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowAppVarAccessDisable {
            get {
                return ResourceManager.GetString("WindowAppVarAccessDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It was used on a window with the following information.
        ///Is this the intended window?
        ///WindowText [{0}]
        ///TypeFullName (.NET) [{1}]
        ///WindowClass [{2}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowInfoAffirmationFormat {
            get {
                return ResourceManager.GetString("WindowInfoAffirmationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than one matching windows were found and a single matching window could not be identified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowManyFound {
            get {
                return ResourceManager.GetString("WindowManyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified window could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowNotFound {
            get {
                return ResourceManager.GetString("WindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #define CODE_ANALYSIS
        ///using System;
        ///using System.Windows;
        ///using System.Windows.Interop;
        ///using System.Windows.Controls;
        ///using System.Drawing;
        ///using Codeer.Friendly.Windows.Grasp.Inside.InApp;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using System.Collections.Generic;
        ///using System.Runtime.InteropServices;
        ///using Codeer.Friendly.Windows.Grasp.Inside;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Windows.Media;
        ///
        ///namespace Codeer.Friendly.Windows.Wpf.Grasp
        ///{
        ///    /// &lt;summary&gt;
        ///    /// WPF解析。
        ///    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WpfAnalyzer {
            get {
                return ResourceManager.GetString("WpfAnalyzer", resourceCulture);
            }
        }
    }
}
